name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: "true"
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.6
    with:
      number-of-agents: 3
      parallel-commands: |
        yarn nx-cloud record -- npx nx workspace-lint
      parallel-commands-on-agents: |
        yarn nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.6
    with:
      number-of-agents: 3

  deploy-pr:
    if: github.event_name == 'pull_request'
    uses: 'mstable/frontend/.github/workflows/deploy-pr.yml@chore/nxcloud'
    secrets: inherit

  deploy-merge:
    if: github.event_name == 'push'
    uses: 'mstable/frontend/.github/workflows/deploy-merge.yml@chore/nxcloud'
    secrets: inherit